### ISSUE TITLE
Can provide detailed deployment methods?

### ISSUE THREAD

**Issue by zgc** [gitonomy/gitonomy#79]
I am a novice git, like your project, but my English level and can't find the detailed deployment method on the Internet, can you provide similar to http://svnmanager.sourceforge.net/index.php?Page=install document?

**Comment by lyrixx** [comment]
Hi @zgc ;

Did you try to follow theses [steps](https://github.com/gitonomy/gitonomy#how-to-install) ?

**Comment by zgc** [comment]
For me this is a beginners are very useful, a lot of content can refer to.

**Comment by zgc** [comment]
I redeploy a git, ssh and http confirmed by normal use,./Install.sh also running, but running web/install.php still appeared the same prompt.

**Comment by zgc** [comment]
@lyrixx @alexandresalome Help, I was not missing some steps?

**Comment by alexandresalome** [comment]
It probably means your git binary is not in your path. How did you install it?

**Comment by zgc** [comment]
@alexandresalome apt-get install git-core http://ppa.launchpad.net/git-core

**Comment by zgc** [comment]
@alexandresalome These days have been experimenting, I found git1.9.1 is normal, but it can not detect git2.4.

**Comment by zgc** [comment]
@alexandresalome Git2.4 version can not hope to repair the installation of bug, thank you

**Comment by zgc** [comment]
The version number is 2.3.0 and 1.9.1 are normal, but not normal 2.4.0.rc1 because more rc1 reason?

**Comment by zgc** [comment]
Development version version src\Gitonomy\Component\Requirements\GitonomyRequirements.php inside the $ res = preg_match ('/ ^ git version ([0-9 \.] +) \ N $ /', stream_get_contents ($ pipes [1 ]), $ vars); wrong
