### ISSUE TITLE
Error runnig install.sh

### ISSUE THREAD

**Issue by nmoller** [gitonomy/gitonomy#80]
I had to declare abstract the class Bundle/Core/Bundle/Entity/Message to run the installation. Without it I got the error message:

 /app.php/install - Uncaught exception 'Doctrine\ORM\Mapping\MappingException' with message 'Entity 'Gitonomy\Bundle\CoreBundle\Entity\Message' has to be part of the discriminator map of 'Gitonomy\Bundle\CoreBundle\Entity\Message' to be properly mapped in the inheritance hierarchy. Alternatively you can make 'Gitonomy\Bundle\CoreBundle\Entity\Message' an abstract class to avoid this exception from occurring.' in /var/www/html/gitonomy/extras/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:679
Stack trace:
#0 /var/www/html/gitonomy/extras/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(338): Doctrine\ORM\Mapping\MappingException::mappedClassNotPartOfDiscriminatorMap('Gitonomy\Bundle...', 'Gitonomy\Bundle...')
#1 [internal function]: Doctrine\ORM\Mapping\ClassMetadataFactory->resolveDiscriminatorValue(Object(Doctrine\ORM\Mapping\ClassMetadata))
#2 /var/www/html/gitonomy/extras/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(80): array_map(Array, Array)
#3 /var/www/html/gitonomy/extras/doctr in /var/www/html/gitonomy/extras/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php on line 679

**Comment by dprevite** [comment]
Getting the same here.

**Comment by nmoller** [comment]
Did the solution work for you? I had not much time to look at it but if it solved that I'll consider doing a more serious work to do a pull request.

**Comment by dprevite** [comment]
Yeah, that seems to have fixed it.
